# Generated by Django 2.0.5 on 2018-06-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=1000)),
                ('share_url', models.CharField(max_length=1000)),
                ('views', models.IntegerField(max_length=10)),
                ('likes', models.IntegerField(max_length=10)),
            ],
        ),
    ]
