# Generated by Django 2.0.5 on 2018-06-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='draw',
            name='views',
            field=models.IntegerField(),
        ),
    ]
