# Generated by Django 2.0.5 on 2018-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180629_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=1000)),
                ('share_url', models.CharField(max_length=1000)),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='draw',
            name='views',
        ),
    ]
