# Generated by Django 2.0.5 on 2018-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180629_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='dance',
            name='video_url',
            field=models.CharField(default='http://...', max_length=1000),
            preserve_default=False,
        ),
    ]
