# Generated by Django 2.0.5 on 2018-06-30 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dance_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dance',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='draw',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
